# Language generation using Transformers

In [1]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

In [2]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModelForCausalLM.from_pretrained("gpt2", output_hidden_states=True)

In [3]:
text = "The judgements "

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

In [5]:
input

tensor([[  464,  2553, 43547,   220]])

In [6]:
# Run the model
max_length = 50
output = model.generate(input, max_length=max_length, top_k=5, top_p=0.95, temperature=0.9, repetition_penalty=1.5)
# output = model.generate(input, max_length=20, do_sample=False)

# Print the output
for i in range(len(output)):
    print('\n',tokenizer.decode(output[i]))

# The judgements  have been given by the courts as to whether a man can or does

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.



 The judgements  of the judges are not based on any evidence of guilt or innocence. The judge is simply a person who has been convicted and sentenced to life in prison for his crimes, but he does so with no regard whatsoever for what happened


In [25]:
output

tensor([[  464,  2553, 43547,   220, 10185,   447,   119, 37929,   314,   892,
           340,   338,   281,  1593,   530,   329,   262,  2055,   284,   787]])

In [8]:
# Print the token ides (of the input and output)
output

tensor([[  464,  2553, 43547,   220, 29773,   225,   423,   587,  1813,   416,
           262,  8028,   355,   284,  1771,   257,   582,   460,   393,   857]])

In [9]:
# Print the input token ids
text = "The judgement"
input = tokenizer(text, return_tensors="pt")['input_ids']
input

tensor([[  464, 23071]])

In [10]:
# This is the embedding matrix of the model
model.transformer.wte # Dimensions are: (Number of tokens in vocabulary, dimension of model)

Embedding(50257, 768)

In [11]:
# Get the embedding vector of token # 464 ('The')
#model.transformer.wte(torch.tensor(464))

In [9]:
text = "The chicken didn't cross the road because it was"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=30, do_sample=True)

# Print the output
print('\n',tokenizer.decode(output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.



 The chicken didn't cross the road because it was moving with the train."

The court found the dog was a dangerous dog.

The
